#
# For running some services on development without tainting your system
#
version: '3'
services:

  mongo:
    image: "mongo"
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/var/lib/mongo/data'
    environment:
      KEY: 'VALUE'

volumes:
  mongo:
